version: '3.3'
services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.0.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    build: ../postgres
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=mysecretpassword
    ports:
     - "5432:5432"
