version: '3.3'
services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      # Load init script to ensure dbs and collections are created
      - ./mongodb/entrypoint-initdb.d/init.js:/docker-entrypoint-initdb.d/init.js:ro
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  postgres:
    build: ../postgres
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=mysecretpassword
    ports:
    - 5432:5432
  minio:
    image: 'bitnami/minio:latest'
    volumes:
      - ./minio/buckets:/data
    ports:
      - '9001:9000'
    environment:
      - MINIO_ROOT_USER=minio-access-key
      - MINIO_ROOT_PASSWORD=minio-secret-key
      - MINIO_DEFAULT_BUCKETS=dp-cantabular-csv-exporter
