version: '3.3'
services:
    dp-cantabular-csv-exporter:
        build:
            context: ../../dp-cantabular-csv-exporter
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../dp-cantabular-csv-exporter:/dp-cantabular-csv-exporter
        depends_on:
            - kafka
            - minio
        ports:
            - 26300:26300
        restart: unless-stopped
        environment:
            BIND_ADDR:                  ":26300"
            KAFKA_ADDR:                 "kafka:9092"
            DATASET_API_URL:            "http://dp-dataset-api:22000"
            RECIPE_API_URL:             "http://dp-recipe-api:22300"
            CANTABULAR_URL:             "http://dp-cantabular-server:8491"
            CANTABULAR_EXT_API_URL:     "http://dp-cantabular-api-ext:8492"
            LOCAL_OBJECT_STORE:         "http://minio:9000"
            MINIO_ACCESS_KEY:           "minio-access-key"
            MINIO_SECRET_KEY:           "minio-secret-key"
            SERVICE_AUTH_TOKEN:         $SERVICE_AUTH_TOKEN
            VAULT_ADDR:                 "http://vault:8200"
            VAULT_TOKEN:                "0000-0000-0000-0000"
#            ENCRYPTION_DISABLED:        "true"
            UPLOAD_BUCKET_NAME:         "public-bucket"
            PRIVATE_UPLOAD_BUCKET_NAME: "private-bucket"
