version: '3.3'
services:
    dp-cantabular-xlsx-exporter:
        build:
            context: ../../dp-cantabular-xlsx-exporter
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../dp-cantabular-xlsx-exporter:/dp-cantabular-xlsx-exporter
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3
            - minio
        ports:
            - 26800:26800
        restart: unless-stopped
        environment:
            BIND_ADDR:                  ":26800"
            KAFKA_ADDR:                 "kafka-1:19092,kafka-2:19092,kafka-3:19092"
            VAULT_ADDR:                 "http://vault:8200"
            DATASET_API_URL:            "http://dp-dataset-api:22000"
            FILTER_API_URL:             "http://dp-filter-api:22100"
            LOCAL_OBJECT_STORE:         "http://minio:9000"
            MINIO_ACCESS_KEY:           "minio-access-key"
            MINIO_SECRET_KEY:           "minio-secret-key"
            SERVICE_AUTH_TOKEN:         $SERVICE_AUTH_TOKEN
            VAULT_TOKEN:                "0000-0000-0000-0000"
            UPLOAD_BUCKET_NAME:         "public-bucket"
            PRIVATE_UPLOAD_BUCKET_NAME: "private-bucket"
            ENCRYPTION_DISABLED:        "false"
