version: '3.3'
services:
    dp-cantabular-filter-flex-api:
        build:
            context: ../../dp-cantabular-filter-flex-api
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../dp-cantabular-filter-flex-api:/dp-cantabular-filter-flex-api
        ports:
            - 27100:27100
        restart: unless-stopped
        environment:
            BIND_ADDR:                   ":27100"
            SERVICE_AUTH_TOKEN:          $SERVICE_AUTH_TOKEN
            CANTABULAR_URL:              "http://dp-cantabular-server:8491"
            ENABLE_PRIVATE_ENDPOINTS:    "true"
            ENABLE_PERMISSIONS_AUTH:     "true"
            ZEBEDEE_URL:                 "http://zebedee:8082"
            MONGODB_BIND_ADDR:           "mongodb:27017"
