version: '3.3'
services:
    dp-download-service:
        build:
            context: ../../dp-download-service
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../dp-download-service:/dp-download-service
        depends_on:
            - kafka
            - minio
            - mongodb
        ports:
            - 23600:23600
        restart: unless-stopped
        environment:
            BIND_ADDR:              ":23600"
            KAFKA_ADDR:             "kafka:9092"
            DATASET_API_URL:        "http://dp-dataset-api:22000"
            LOCAL_OBJECT_STORE:     "http://minio:9000"
            ZEBEDEE_URL:            "http://zebedee:8082"
            MINIO_ACCESS_KEY:       "minio-access-key"
            MINIO_SECRET_KEY:       "minio-secret-key"
            SERVICE_AUTH_TOKEN:     $SERVICE_AUTH_TOKEN
            ENCRYPTION_DISABLED:    "true"
            BUCKET_NAME:            "private-bucket"
