version: '3.3'
services:
    dp-import-cantabular-dataset:
        build:
            context: ../../dp-import-cantabular-dataset
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../dp-import-cantabular-dataset:/dp-import-cantabular-dataset
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3
        ports:
            - 26100:26100
        restart: unless-stopped
        environment:
            BIND_ADDR:              ":26100"
            KAFKA_ADDR:             "kafka-1:19092,kafka-2:19092,kafka-3:19092"
            DATASET_API_URL:        "http://dp-dataset-api:22000"
            RECIPE_API_URL:         "http://dp-recipe-api:22300"
            CANTABULAR_URL:         "http://dp-cantabular-server:8491"
            CANTABULAR_EXT_API_URL: "http://dp-cantabular-api-ext:8492"
            IMPORT_API_URL:         "http://dp-import-api:21800"
            SERVICE_AUTH_TOKEN:     $SERVICE_AUTH_TOKEN
