version: '3.3'
services:
    dp-import-cantabular-dimension-options:
        build:
            context: ../../dp-import-cantabular-dimension-options
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../dp-import-cantabular-dimension-options:/dp-import-cantabular-dimension-options
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3
        ports:
            - 26200:26200
        restart: unless-stopped
        environment:
            BIND_ADDR:          ":26200"
            KAFKA_ADDR:         "kafka-1:19092,kafka-2:19092,kafka-3:19092"
            DATASET_API_URL:    "http://dp-dataset-api:22000"
            CANTABULAR_URL:     "http://dp-cantabular-server:8491"
            IMPORT_API_URL:     "http://dp-import-api:21800"
            SERVICE_AUTH_TOKEN: $SERVICE_AUTH_TOKEN
