version: '3.3'
services:
    dp-publishing-dataset-controller:
        build:
            context: ../../dp-publishing-dataset-controller
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../dp-publishing-dataset-controller:/dp-publishing-dataset-controller
        ports:
            - 24000:24000
        environment:
            BIND_ADDR:          ":24000"
            API_ROUTER_URL:     "http://dp-api-router:23200/v1"
