version: '3.3'
services:
    dp-population-types-api:
        build:
            context: ../../dp-population-types-api
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        ports:
            - 27300:27300
        volumes:
            - ../../dp-population-types-api:/dp-population-types-api
        restart: unless-stopped
        environment:
            BIND_ADDR:                ":27300"
            CANTABULAR_URL:           "http://dp-cantabular-server:8491"
            CANTABULAR_API_EXT_URL:   "http://dp-cantabular-api-ext:8492"
            DATASET_API_URL:          "http://dp-dataset-api:22000"
            ZEBEDEE_URL:              "http://zebedee:8082"
            SERVICE_AUTH_TOKEN:        $SERVICE_AUTH_TOKEN
            ENABLE_PRIVATE_ENDPOINTS: "true"
            MONGODB_BIND_ADDR:        "mongodb:27017"
            CENSUS_OBSERVATIONS_FF:   "true"
