version: '3.3'
services:
  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - ./elk/logstash/logstash.conf:/etc/logstash/logstash.conf
    command: logstash -f /etc/logstash/logstash.conf
    depends_on:
      - elasticsearch
    ports:
    - '5044:5044'
    - '5044:5044/udp'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - ./elk/elasticsearch_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
    - '9200:9200'
    - '9300:9300'

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
