filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- type: container
  paths:
   - '/var/lib/docker/containers/*/*.log'
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  processors:
   - add_cloud_metadata: ~

#filebeat.autodiscover:
#  providers:
#    - type: docker
#      paths:
#       - '/var/lib/docker/containers/*/*.log'
#      hints.enabled: true


output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  allow_older_versions: true  
