version: '3.3'
services:
    florence:
        build:
            context: ../../florence
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../../florence:/florence
        ports:
            - 8081:8081
        depends_on:
            - zebedee
            - dp-frontend-router
            - dp-frontend-dataset-controller
        restart: unless-stopped
        environment:
            ENCRYPTION_DISABLED:    "true"
            ENABLE_DATASET_IMPORT:  "true"
            API_ROUTER_URL:         "http://dp-api-router:23200"
            ROUTER_URL:             "http://dp-frontend-router:20000"
            DATASET_CONTROLLER_URL: "http://dp-publishing-dataset-controller:24000"
        logging:
            driver: gelf
            options:
              gelf-address: "udp://127.0.0.1:5044"
              tag: "florence"
