version: '3.3'
services:
    the-train:
        build:
            context: ../../the-train
            dockerfile: Dockerfile
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3
        ports:
            - 8084:8084
        restart: unless-stopped
        user: ${UID-1000}:${GID-1000}
        volumes:
            - $zebedee_root:/$zebedee_root
        environment:
            TRANSACTION_STORE:           "$zebedee_root/zebedee/transactions"
            WEBSITE:                     "$zebedee_root/zebedee/master"
            PUBLISHING_THREAD_POOL_SIZE: 100
            PORT:                        8084
            DP_COLOURED_LOGGING:         "true"
            DP_LOGGING_FORMAT:           "pretty_json"
            PUBLISHING_THREAD_POOL_SIZE: 100
            MAX_FILE_UPLOAD_SIZE_MB:     -1
            MAX_REQUEST_SIZE_MB:         -1
            FILE_THRESHOLD_SIZE_MB:      0
