version: '3.3'
services:
    zebedee:
        build:
            context: ../../zebedee
            dockerfile: Dockerfile
        volumes:
            - ../../dp-recipe-api:/dp-recipe-api
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3
        ports:
            - 8082:8082
        volumes:
            - $zebedee_root:/zebedee_root
        restart: unless-stopped
        environment:
            DATASET_API_URL:            "http://dp-dataset-api:22000"
            DATASET_API_AUTH_TOKEN:     "FD0108EA-825D-411C-9B1D-41EF7727F465"
            ENABLE_DATASET_IMPORT:      "true"
            FORMAT_LOGGING:             "true"
            JAVA_OPTS:                  " -Xmx1204m -Xdebug -Xrunjdwp:transport=dt_socket,address=8002,server=y,suspend=n"
            PORT:                       "8082"
            RESTOLINO_STATIC:           "src/main/resources/files"
            RESTOLINO_CLASSES:          "zebedee-cms/target/classes"
            PACKAGE_PREFIX:             "com.github.onsdigital.zebedee"
            zebedee_root:               "/zebedee_root"
            SERVICE_AUTH_TOKEN:         $SERVICE_AUTH_TOKEN
            publish_url:                "http://the-train:8084"

