version: '2'
services:
  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
     - "9300:9300"
     - "9200:9200"
  highcharts:
    image: onsdigital/highcharts-export-node
    ports:
     - "9999:8080"
  postgres:
    image: postgres:9.6
    build: ./postgres
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=mysecretpassword
    ports:
     - "5432:5432"
