version: '2'
services:
  elasticsearch:
    image: elasticsearch
    ports:
     - "9300:9300"
     - "9200:9200"
  highcharts:
    image: onsdigital/highcharts-export-docker
    ports:
     - "9999:8080"
  postgres:
    build: ./postgres
    environment: 
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=mysecretpassword
    ports:
     - "5432:5432"
