# Include common make targets
include ../common.mk

.PHONY: init
init: base-init
	# Add stack specific initialisation logic here
	@$(SCRIPTS_DIR)/zebedee-content.sh

# Add any stack specific helper targets here
