extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "jaeger.service.local:4317"
    tls:
      insecure: true

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
    metrics:
      receivers: [otlp]
      exporters: [logging]

