#!/bin/bash
echo "Setting redirects - make sure that Redis is running on localhost port 6379"
set -x
redis-cli SET "fwd:/economy/mybulletin" "/finance/mybulletin"
redis-cli SET "fwd:/economy/furtherreading/mybulletin" "/finance/mybulletin"
redis-cli SADD rev:/finance/mybulletin "/economy/mybulletin" "/economy/furtherreading/mybulletin"
redis-cli SET "fwd:/economy/economicoutputandproductivity/mybulletin" "/finance/economicoutputandproductivity/mybulletin"
redis-cli SET "fwd:/economy/furtherreading/economicoutputandproductivity/mybulletin" "/finance/economicoutputandproductivity/mybulletin"
redis-cli SADD rev:/finance/economicoutputandproductivity/mybulletin "/economy/economicoutputandproductivity/mybulletin" "/economy/furtherreading/economicoutputandproductivity/mybulletin"
redis-cli SET "fwd:/economy/environmentalaccounts/mybulletin" "/finance/environmentalaccounts/mybulletin"
redis-cli SET "fwd:/economy/furtherreading/environmentalaccounts/mybulletin" "/finance/environmentalaccounts/mybulletin"
redis-cli SADD rev:/finance/environmentalaccounts/mybulletin "/economy/environmentalaccounts/mybulletin" "/economy/furtherreading/environmentalaccounts/mybulletin"
redis-cli SET "fwd:/economy/grossvalueaddedgva/mybulletin" "/finance/grossvalueaddedgva/mybulletin"
redis-cli SET "fwd:/economy/grossvalueaddedgva/furtherreading/mybulletin" "/finance/grossvalueaddedgva/mybulletin"
redis-cli SADD rev:/finance/grossvalueaddedgva/mybulletin "/economy/grossvalueaddedgva/mybulletin" "/economy/grossvalueaddedgva/furtherreading/mybulletin"
redis-cli SET "fwd:/economy/inflationandpriceindices/mybulletin" "/finance/inflationandpriceindices/mybulletin"
redis-cli SET "fwd:/economy/furtherreading/inflationandpriceindices/mybulletin" "/finance/inflationandpriceindices/mybulletin"
redis-cli SADD rev:/finance/inflationandpriceindices/mybulletin "/economy/inflationandpriceindices/mybulletin" "/economy/furtherreading/inflationandpriceindices/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/mybulletin" "/commerce/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/furtherreading/mybulletin" "/commerce/mybulletin"
redis-cli SADD rev:/commerce/mybulletin "/businessindustryandtrade/mybulletin" "/businessindustryandtrade/furtherreading/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/business/mybulletin" "/commerce/trade/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/business/furtherreading/mybulletin" "/commerce/trade/mybulletin"
redis-cli SADD rev:/commerce/trade/mybulletin "/businessindustryandtrade/business/mybulletin" "/businessindustryandtrade/business/furtherreading/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/constructionindustry/mybulletin" "/commerce/construction/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/constructionindustry/furtherreading/mybulletin" "/commerce/construction/mybulletin"
redis-cli SADD rev:/commerce/construction/mybulletin "/businessindustryandtrade/constructionindustry/mybulletin" "/businessindustryandtrade/constructionindustry/furtherreading/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/itandinternetindustry/mybulletin" "/commerce/itandinternetindustry/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/itandinternetindustry/furtherreading/mybulletin" "/commerce/itandinternetindustry/mybulletin"
redis-cli SADD rev:/commerce/itandinternetindustry/mybulletin "/businessindustryandtrade/itandinternetindustry/mybulletin" "/businessindustryandtrade/itandinternetindustry/furtherreading/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/retailindustry/mybulletin" "/commerce/retail/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/retailindustry/furtherreading/mybulletin" "/commerce/retail/mybulletin"
redis-cli SADD rev:/commerce/retail/mybulletin "/businessindustryandtrade/retailindustry/mybulletin" "/businessindustryandtrade/retailindustry/furtherreading/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/mybulletin" "/workforce/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/furtherreading/mybulletin" "/workforce/mybulletin"
redis-cli SADD rev:/workforce/mybulletin "/employmentandlabourmarket/mybulletin" "/employmentandlabourmarket/furtherreading/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peopleinwork/mybulletin" "/workforce/employedpeople/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peopleinwork/furtherreading/mybulletin" "/workforce/employedpeople/mybulletin"
redis-cli SADD rev:/workforce/employedpeople/mybulletin "/employmentandlabourmarket/peopleinwork/mybulletin" "/employmentandlabourmarket/peopleinwork/furtherreading/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peoplenotinwork/mybulletin" "/workforce/unemployedpeople/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peoplenotinwork/furtherreading/mybulletin" "/workforce/unemployedpeople/mybulletin"
redis-cli SADD rev:/workforce/unemployedpeople/mybulletin "/employmentandlabourmarket/peoplenotinwork/mybulletin" "/employmentandlabourmarket/peoplenotinwork/furtherreading/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peopleinwork/earningsandworkinghours/mybulletin" "/workforce/earnings/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peopleinwork/earningsandworkinghours/furtherreading/mybulletin" "/workforce/earnings/mybulletin"
redis-cli SADD rev:/workforce/earnings/mybulletin "/employmentandlabourmarket/peopleinwork/earningsandworkinghours/mybulletin" "/employmentandlabourmarket/peopleinwork/earningsandworkinghours/furtherreading/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/mybulletin" "/workforce/unemployedpeople/benefits/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/furtherreading/mybulletin" "/workforce/unemployedpeople/benefits/mybulletin"
redis-cli SADD rev:/workforce/unemployedpeople/benefits/mybulletin "/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/mybulletin" "/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/furtherreading/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/mybulletin" "/society/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/furtherreading/mybulletin" "/society/mybulletin"
redis-cli SADD rev:/society/mybulletin "/peoplepopulationandcommunity/mybulletin" "/peoplepopulationandcommunity/furtherreading/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/culturalidentity/mybulletin" "/society/culturalidentity/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/culturalidentity/furtherreading/mybulletin" "/society/culturalidentity/mybulletin"
redis-cli SADD rev:/society/culturalidentity/mybulletin "/peoplepopulationandcommunity/culturalidentity/mybulletin" "/peoplepopulationandcommunity/culturalidentity/furtherreading/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/educationandchildcare/mybulletin" "/society/education/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/educationandchildcare/furtherreading/mybulletin" "/society/education/mybulletin"
redis-cli SADD rev:/society/education/mybulletin "/peoplepopulationandcommunity/educationandchildcare/mybulletin" "/peoplepopulationandcommunity/educationandchildcare/furtherreading/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/elections/mybulletin" "/society/politics/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/elections/furtherreading/mybulletin" "/society/politics/mybulletin"
redis-cli SADD rev:/society/politics/mybulletin "/peoplepopulationandcommunity/elections/mybulletin" "/peoplepopulationandcommunity/elections/furtherreading/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/healthandsocialcare/childhealth/mybulletin" "/society/healthandsocialcare/childhealth/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/healthandsocialcare/childhealth/furtherreading/mybulletin" "/society/healthandsocialcare/childhealth/mybulletin"
redis-cli SADD rev:/society/healthandsocialcare/childhealth/mybulletin "/peoplepopulationandcommunity/healthandsocialcare/childhealth/mybulletin" "/peoplepopulationandcommunity/healthandsocialcare/childhealth/furtherreading/mybulletin"
set +x
echo "40 forward and 20 reverse redirect keys and values now set in Redis"
