#!/bin/bash
echo "Setting redirects - make sure that Redis is running on localhost port 6379"
set -x
redis-cli SET "/economy/mybulletin" "/finance/mybulletin"
redis-cli SET "/economy/economicoutputandproductivity/mybulletin" "/finance/economicoutputandproductivity/mybulletin"
redis-cli SET "/economy/environmentalaccounts/mybulletin" "/finance/environmentalaccounts/mybulletin"
redis-cli SET "/economy/grossvalueaddedgva/mybulletin" "/finance/grossvalueaddedgva/mybulletin"
redis-cli SET "/economy/inflationandpriceindices/mybulletin" "/finance/inflationandpriceindices/mybulletin"
redis-cli SET "/businessindustryandtrade/mybulletin" "/commerce/mybulletin"
redis-cli SET "/businessindustryandtrade/business/mybulletin" "/commerce/trade/mybulletin"
redis-cli SET "/businessindustryandtrade/constructionindustry/mybulletin" "/commerce/construction/mybulletin"
redis-cli SET "/businessindustryandtrade/itandinternetindustry/mybulletin" "/commerce/itandinternetindustry/mybulletin"
redis-cli SET "/businessindustryandtrade/retailindustry/mybulletin" "/commerce/retail/mybulletin"
redis-cli SET "/employmentandlabourmarket/mybulletin" "/workforce/mybulletin"
redis-cli SET "/employmentandlabourmarket/peopleinwork/mybulletin" "/workforce/employedpeople/mybulletin"
redis-cli SET "/employmentandlabourmarket/peoplenotinwork/mybulletin" "/workforce/unemployedpeople/mybulletin"
redis-cli SET "/employmentandlabourmarket/peopleinwork/earningsandworkinghours/mybulletin" "/workforce/earnings/mybulletin"
redis-cli SET "/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/mybulletin" "/workforce/unemployedpeople/benefits/mybulletin"
redis-cli SET "/peoplepopulationandcommunity/mybulletin" "/society/mybulletin"
redis-cli SET "/peoplepopulationandcommunity/culturalidentity/mybulletin" "/society/culturalidentity/mybulletin"
redis-cli SET "/peoplepopulationandcommunity/educationandchildcare/mybulletin" "/society/education/mybulletin"
redis-cli SET "/peoplepopulationandcommunity/elections/mybulletin" "/society/politics/mybulletin"
redis-cli SET "/peoplepopulationandcommunity/healthandsocialcare/childhealth/mybulletin" "/society/healthandsocialcare/childhealth/mybulletin"
set +x
echo "20 redirect keys and values now set in Redis"
