#!/bin/bash
echo "Setting redirects - make sure that Redis is running on localhost port 6379"
set -x
redis-cli SET "fwd:/economy/mybulletin" "/finance/mybulletin"
redis-cli SET "rev:/finance/mybulletin" "/economy/mybulletin"
redis-cli SET "fwd:/economy/economicoutputandproductivity/mybulletin" "/finance/economicoutputandproductivity/mybulletin"
redis-cli SET "rev:/finance/economicoutputandproductivity/mybulletin" "/economy/economicoutputandproductivity/mybulletin"
redis-cli SET "fwd:/economy/environmentalaccounts/mybulletin" "/finance/environmentalaccounts/mybulletin"
redis-cli SET "rev:/finance/environmentalaccounts/mybulletin" "/economy/environmentalaccounts/mybulletin"
redis-cli SET "fwd:/economy/grossvalueaddedgva/mybulletin" "/finance/grossvalueaddedgva/mybulletin"
redis-cli SET "rev:/finance/grossvalueaddedgva/mybulletin" "/economy/grossvalueaddedgva/mybulletin"
redis-cli SET "fwd:/economy/inflationandpriceindices/mybulletin" "/finance/inflationandpriceindices/mybulletin"
redis-cli SET "rev:/finance/inflationandpriceindices/mybulletin" "/economy/inflationandpriceindices/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/mybulletin" "/commerce/mybulletin"
redis-cli SET "rev:/commerce/mybulletin" "/businessindustryandtrade/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/business/mybulletin" "/commerce/trade/mybulletin"
redis-cli SET "rev:/commerce/trade/mybulletin" "/businessindustryandtrade/business/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/constructionindustry/mybulletin" "/commerce/construction/mybulletin"
redis-cli SET "rev:/commerce/construction/mybulletin" "/businessindustryandtrade/constructionindustry/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/itandinternetindustry/mybulletin" "/commerce/itandinternetindustry/mybulletin"
redis-cli SET "rev:/commerce/itandinternetindustry/mybulletin" "/businessindustryandtrade/itandinternetindustry/mybulletin"
redis-cli SET "fwd:/businessindustryandtrade/retailindustry/mybulletin" "/commerce/retail/mybulletin"
redis-cli SET "rev:/commerce/retail/mybulletin" "/businessindustryandtrade/retailindustry/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/mybulletin" "/workforce/mybulletin"
redis-cli SET "rev:/workforce/mybulletin" "/employmentandlabourmarket/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peopleinwork/mybulletin" "/workforce/employedpeople/mybulletin"
redis-cli SET "rev:/workforce/employedpeople/mybulletin" "/employmentandlabourmarket/peopleinwork/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peoplenotinwork/mybulletin" "/workforce/unemployedpeople/mybulletin"
redis-cli SET "rev:/workforce/unemployedpeople/mybulletin" "/employmentandlabourmarket/peoplenotinwork/mybulletin"   
redis-cli SET "fwd:/employmentandlabourmarket/peopleinwork/earningsandworkinghours/mybulletin" "/workforce/earnings/mybulletin"
redis-cli SET "rev:/workforce/earnings/mybulletin" "/employmentandlabourmarket/peopleinwork/earningsandworkinghours/mybulletin"
redis-cli SET "fwd:/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/mybulletin" "/workforce/unemployedpeople/benefits/mybulletin"
redis-cli SET "rev:/workforce/unemployedpeople/benefits/mybulletin" "/employmentandlabourmarket/peoplenotinwork/outofworkbenefits/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/mybulletin" "/society/mybulletin"
redis-cli SET "rev:/society/mybulletin" "/peoplepopulationandcommunity/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/culturalidentity/mybulletin" "/society/culturalidentity/mybulletin"
redis-cli SET "rev:/society/culturalidentity/mybulletin" "/peoplepopulationandcommunity/culturalidentity/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/educationandchildcare/mybulletin" "/society/education/mybulletin"
redis-cli SET "rev:/society/education/mybulletin" "/peoplepopulationandcommunity/educationandchildcare/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/elections/mybulletin" "/society/politics/mybulletin"
redis-cli SET "rev:/society/politics/mybulletin" "/peoplepopulationandcommunity/elections/mybulletin"
redis-cli SET "fwd:/peoplepopulationandcommunity/healthandsocialcare/childhealth/mybulletin" "/society/healthandsocialcare/childhealth/mybulletin"
redis-cli SET "rev:/society/healthandsocialcare/childhealth/mybulletin" "/peoplepopulationandcommunity/healthandsocialcare/childhealth/mybulletin"
set +x
echo "20 forward and 20 reverse redirect keys and values now set in Redis"
