version: '3.3'
services:

  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - "discovery.type=single-node"

  sitewideelasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    expose:
      - "9300" # exposed port to docker network so that the broker is reachable by other brokers, value needs to match PLAINTEXT port
      - "9200"
    ports:
      # Set alternative localhost ports to prevent port clash.
      - 11300:9300
      - 11200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"

  cmdelasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    expose:
      - "9300" # exposed port to docker network so that the broker is reachable by other brokers, value needs to match PLAINTEXT port
      - "9200"
    ports:
      # Set alternative ports to prevent port clash.
      - 10300:9300
      - 10200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
