services:
  highcharts:
    image: onsdigital/highcharts-export-node
    ports:
      - "9999:8080"
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:8080/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
