services:
  http-echo:
    platform: linux/amd64
    image: hashicorp/http-echo:alpine
    command: ["-text", "http-echo"]
    ports:
      - 15678:5678
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:5678/"]
      interval: 60s
      timeout: 10s
      retries: 10
