version: '3.3'
services:
  kowl:
    image: quay.io/cloudhut/kowl:master
    ports:
      - '9888:8080'
    environment:
      KAFKA_BROKERS: kafka-1:19092,kafka-2:19093,kafka-3:19094

  kouncil:
    image: consdata/kouncil:latest
    ports:
      - '8888:8080'
    environment:
      bootstrapServers:
        kafka-1:19092
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
