services:
  localstack:
    image: localstack/localstack
    ports:
      - 14566:4566
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
    volumes:
      - ../../provisioning/localstack/index.html:/root/index.html
      - ../../provisioning/localstack:/etc/localstack/init/ready.d/      
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
