version: '3.3'
services:
  mongodb:
    image: mongo:3.6
    expose:
      - "27017"
    ports:
      - 27017:27017
    # volumes:
      # - ../../provisioning/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
