version: '3'
services:  
  postgis:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432
    volumes:
      - ../../provisioning/postgis:/docker-entrypoint-initdb.d:ro