services:
  redis:
    image: redis:7.2
    expose:
      - "6379"
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s
