version: '3.3'
services:
  vault:
    image: hashicorp/vault:latest
    ports:
     - 8200:8200
    restart: always
    entrypoint: vault server -dev -dev-kv-v1 -dev-root-token-id="0000-0000-0000-0000"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: '0000-0000-0000-0000'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'