version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:2.4.2
    ports:
     - 9300:9300
     - 9200:9200
    environment:
     - "discovery.type=single-node"
  sitewideelasticsearch:
    profiles: 
      - "elasticsearch"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      # Set alternative ports to prevent port clash.
      - 11300:9300
      - 11200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"