services:
  elasticsearch:
    extends:
      file: ${PATH_MANIFESTS}/deps/elasticsearch.yml
      service: elasticsearch
  cmdelasticsearch:
    extends:
      file: ${PATH_MANIFESTS}/deps/elasticsearch.yml
      service: cmdelasticsearch
  sitewideelasticsearch:
    extends:
      file: ${PATH_MANIFESTS}/deps/elasticsearch.yml
      service: sitewideelasticsearch
  highcharts:
    extends:
      file: ${PATH_MANIFESTS}/deps/highcharts.yml
      service: highcharts
  mongodb:
    extends:
      file: ${PATH_MANIFESTS}/deps/mongo.yml
      service: mongodb
    volumes:
      - ${PATH_PROVISIONING}/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
  zookeeper-1:
    extends:
      file: ${PATH_MANIFESTS}/deps/kafka.yml
      service: zookeeper-1
  kafka-1:
    extends:
      file: ${PATH_MANIFESTS}/deps/kafka.yml
      service: kafka-1
    depends_on:
      - zookeeper-1
  kafka-2:
    extends:
      file: ${PATH_MANIFESTS}/deps/kafka.yml
      service: kafka-2
    depends_on:
      - zookeeper-1
  kafka-3:
    extends:
      file: ${PATH_MANIFESTS}/deps/kafka.yml
      service: kafka-3
    depends_on:
      - zookeeper-1
  mathjax:
    extends:
      file: ${PATH_MANIFESTS}/core-ons/mathjax-api.yml
      service: mathjax
