services:
  dis-bundle-api:
    x-repo-url: "https://github.com/ONSdigital/dis-bundle-api"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dis-bundle-api
      dockerfile: Dockerfile.local
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dis-bundle-api:/dis-bundle-api
    expose:
      - "29800"
    ports:
      - 29800:29800
    environment:
      BIND_ADDR: ":29800"
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:29800/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
    entrypoint: make debug
