services:
  dp-dimension-extractor:
    x-repo-url: "https://github.com/ONSdigital/dp-dimension-extractor"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dp-dimension-extractor
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dp-dimension-extractor:/dp-dimension-extractor
    expose:
      - "21400"
    ports:
      - 21400:21400
    restart: unless-stopped
    environment:
      BIND_ADDR:                   ":21400"
      DATASET_API_URL:             ${DATASET_API_URL:-http://dp-dataset-api:22000}
      KAFKA_ADDR:                  ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_MAX_BYTES:             ${KAFKA_MAX_BYTES:-2000000}
      KAFKA_VERSION:               ${KAFKA_VERSION:-3.1.0}
      LOCALSTACK_HOST:             ${LOCALSTACK_URL:-http://localstack:4566}
      IS_PUBLISHING:               ${IS_PUBLISHING:-true}
      VAULT_ADDR:                  ${VAULT_ADDR:-http://vault:8200}
      ZEBEDEE_URL:                 ${ZEBEDEE_URL:-http://zebedee:8082}
      SERVICE_AUTH_TOKEN:          ${SERVICE_AUTH_TOKEN:?please define a valid SERVICE_AUTH_TOKEN in your local system}
      VAULT_TOKEN:                 "0000-0000-0000-0000"
      ENCRYPTION_DISABLED:         "true"
      NEPTUNE_TLS_SKIP_VERIFY:     ${NEPTUNE_TLS_SKIP_VERIFY:-true}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:21400/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
