services:
  dp-feedback-api:
    x-repo-url: "https://github.com/ONSdigital/dp-feedback-api"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dp-feedback-api
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dp-feedback-api:/dp-feedback-api
    expose:
      - "28600"
    ports:
      - 28600:28600
    restart: unless-stopped
    environment:
      BIND_ADDR:                          ":28600"
      GRACEFUL_SHUTDOWN_TIMEOUT:          ${GRACEFUL_SHUTDOWN_TIMEOUT:-5s}
      HEALTHCHECK_INTERVAL:               ${HEALTHCHECK_INTERVAL:-30s}
      HEALTHCHECK_CRITICAL_TIMEOUT:       ${HEALTHCHECK_CRITICAL_TIMEOUT:-90s}
      MAIL_HOST:                          ${MAIL_HOST:-mailhog}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:28600/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
