version: "3.3"
services:
  dp-frontend-homepage-controller:
    x-repo-url: "https://github.com/ONSdigital/dp-frontend-homepage-controller"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dp-frontend-homepage-controller
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dp-frontend-homepage-controller:/dp-frontend-homepage-controller
    expose:
      - "24400"
    ports:
      - 24400:24400
    restart: unless-stopped
    environment:
      BIND_ADDR:                      ":24400"
      API_ROUTER_URL:                 ${API_ROUTER_URL:-http://dp-api-router:23200}/v1
      CENSUS_TOPIC_ID:                ${CENSUS_TOPIC_ID:-4445}
      DEBUG:                          ${DEBUG:-false}
      ENABLE_CENSUS_TOPIC_SUBSECTION: ${ENABLE_CENSUS_TOPIC_SUBSECTION:-false}
      ENABLE_NEW_NAVBAR:              ${ENABLE_NEW_NAVBAR:-false}
      IS_PUBLISHING_MODE:             ${IS_PUBLISHING:-false}
      SERVICE_AUTH_TOKEN:             ${SERVICE_AUTH_TOKEN:?please define a valid SERVICE_AUTH_TOKEN in your local system}
      SITE_DOMAIN:                    ${SITE_DOMAIN:-localhost}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:24400/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
