version: "3.3"
services:
  dp-hierarchy-builder:
    build:
      context: ${ROOT_IMAGE_API:-../../../../dp-hierarchy-builder}
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${ROOT_IMAGE_API:-../../../../dp-hierarchy-builder}:/dp-hierarchy-builder
    expose:
      - "22700"
    ports:
      - 22700:22700
    restart: unless-stopped
    environment:
      BIND_ADDR:                   ":22700"
      MONGODB_BIND_ADDR:           ${MONGODB_BIND_ADDR:-mongodb:27017}
      KAFKA_ADDR:                  ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_MAX_BYTES:             ${KAFKA_MAX_BYTES:-2000000}
      KAFKA_VERSION:               ${KAFKA_VERSION:-3.1.0}
      IS_PUBLISHING:               ${IS_PUBLISHING:-true}
      ZEBEDEE_URL:                 ${ZEBEDEE_URL:-http://zebedee:8082}
      NEPTUNE_TLS_SKIP_VERIFY:     ${NEPTUNE_TLS_SKIP_VERIFY:-true}
      GRAPH_ADDR:                  ${GRAPH_ADDR:-wss://host.docker.internal:8182/gremlin}
      GRAPH_DRIVER_TYPE:           ${GRAPH_DRIVER_TYPE:-neptune}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:22700/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
