version: "3.3"
services:
  dp-image-api:
    build:
      context: ../../../../dp-image-api
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ../../../../dp-image-api:/dp-image-api
    expose:
      - "24700"
    ports:
      - 24700:24700
    restart: unless-stopped
    environment:
      BIND_ADDR:                   ":24700"
      IMAGE_API_URL:               ${IMAGE_API_URL:-http://dp-image-api:24700}
      MONGODB_BIND_ADDR:           ${MONGODB_BIND_ADDR:-mongodb:27017}
      KAFKA_ADDR:                  ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_MAX_BYTES:             ${KAFKA_MAX_BYTES:-2000000}
      KAFKA_VERSION:               ${KAFKA_VERSION:-3.1.0}
      IMAGE_UPLOADED_TOPIC:        ${IMAGE_UPLOADED_TOPIC:-image-uploaded}
      STATIC_FILE_PUBLISHED_TOPIC: ${STATIC_FILE_PUBLISHED_TOPIC:-static-file-published}
      IS_PUBLISHING:               ${IS_PUBLISHING:-true}
      ZEBEDEE_URL:                 ${ZEBEDEE_URL:-http://zebedee:8082}
      DOWNLOAD_SERVICE_URL:        ${DOWNLOAD_SERVICE_URL:-http://dp-download-service:23600}
