version: "3.3"
services:
  dp-observation-extractor:
    build:
      context: ${ROOT_IMAGE_API:-../../../../dp-observation-extractor}
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${ROOT_IMAGE_API:-../../../../dp-observation-extractor}:/dp-observation-extractor
    expose:
      - "21600"
    ports:
      - 21600:21600
    restart: unless-stopped
    environment:
      BIND_ADDR:                   ":21600"
      MONGODB_BIND_ADDR:           ${MONGODB_BIND_ADDR:-mongodb:27017}
      KAFKA_ADDR:                  ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_MAX_BYTES:             ${KAFKA_MAX_BYTES:-2000000}
      LOCALSTACK_HOST:             ${LOCALSTACK_URL:-http://localstack:4566}
      KAFKA_VERSION:               ${KAFKA_VERSION:-3.1.0}
      IS_PUBLISHING:               ${IS_PUBLISHING:-true}
      ZEBEDEE_URL:                 ${ZEBEDEE_URL:-http://zebedee:8082}
      VAULT_ADDR:                  ${VAULT_ADDR:-http://vault:8200}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:21600/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
