version: "3.3"
services:
  dp-release-calendar-api:
    x-repo-url: "https://github.com/ONSdigital/dp-release-calendar-api"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dp-release-calendar-api
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dp-release-calendar-api:/dp-release-calendar-api
    expose:
      - "27800"
    ports:
      - 27800:27800
    restart: unless-stopped
    environment:
      BIND_ADDR:                ":27800"
      API_ROUTER_URL:           ${API_ROUTER_URL:-http://dp-api-router:23200}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:27800/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
