version: '3.3'
services:
  dp-static-file-publisher:
    build:
      context: ../../../../dp-static-file-publisher
      dockerfile: Dockerfile-local
    ports:
      - 24900:24900
    environment:
      HEALTHCHECK_INTERVAL:               ${HEALTHCHECK_INTERVAL:-30s}
      BIND_ADDR:                          ':24900'
      GRACEFUL_SHUTDOWN_TIMEOUT:          '30s'
      HEALTHCHECK_CRITICAL_TIMEOUT:       '30s'
      VAULT_TOKEN:                        '0000-0000-0000-0000'
      VAULT_ADDR:                         'http://vault:8200'
      VAULT_PATH:                         'secret/shared/psk'
      VAULT_RETRIES:                      '3'
      KAFKA_ADDR:                         'kafka:9092'
      KAFKA_PRODUCER_MIN_BROKERS_HEALTHY: '1'
      KAFKA_VERSION:                      '3.1.0'
      KAFKA_MAX_BYTES:                    '2000000'
      KAFKA_MIN_HEALTHY_BROKERS:          '1'
      STATIC_FILE_PUBLISHED_TOPIC:        'static-file-published'
      STATIC_FILE_PUBLISHED_TOPIC_V2:     'static-file-published-v2'
      S3_PRIVATE_BUCKET_NAME:             'testing'
      S3_PUBLIC_BUCKET_NAME:              'testing-public'
      FILES_API_URL:                      ${FILES_API_URL:-http://dp-files-api:26900}
      CONSUMER_GROUP:                     'dp-static-file-publisher'
      S3_LOCAL_URL:                       'http://localstack:4566'
      S3_LOCAL_ID:                        'test'
      S3_LOCAL_SECRET:                    'test'
      IMAGE_API_URL:                      ${IMAGE_API_URL:-http://dp-image-api:24700}
    volumes:
      - ../../../../dp-static-file-publisher:/service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:24900/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    entrypoint: make debug