version: "3.3"
services:
  dp-search-data-finder:
    x-repo-url: "https://github.com/ONSdigital/dp-search-data-finder"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dp-search-data-finder
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dp-search-data-finder:/dp-search-data-finder
    expose:
      - "28000"
    ports:
      - 28000:28000
    restart: unless-stopped
    environment:
      API_ROUTER_URL:      ${API_ROUTER_URL:-http://dp-api-router:23200/v1}
      ENABLE_PUBLISH_CONTENT_UPDATED_TOPIC: ${ENABLE_PUBLISH_CONTENT_UPDATED_TOPIC:-true}
      BIND_ADDR:          ":28000"
      KAFKA_ADDR:         ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_VERSION:      ${KAFKA_VERSION:-3.1.0}
      ELASTIC_SEARCH_URL: ${ELASTIC_SEARCH_URL:-http://sitewideelasticsearch:9200}
      SERVICE_AUTH_TOKEN: ${SERVICE_AUTH_TOKEN:?please define a valid SERVICE_AUTH_TOKEN in your local system}
      ZEBEDEE_URL:        ${ZEBEDEE_URL:-http://zebedee:8082}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:28000/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
