version: "3.3"
services:
  dp-search-reindex-tracker:
    x-repo-url: "https://github.com/ONSdigital/dp-search-reindex-tracker"
    build:
      context: ${DP_REPO_DIR:-../../../..}/dp-search-reindex-tracker
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${DP_REPO_DIR:-../../../..}/dp-search-reindex-tracker:/dp-search-reindex-tracker
    expose:
      - "28500"
    ports:
      - 28500:28500
    restart: unless-stopped
    environment:
      BIND_ADDR:          ":28500"
      ELASTIC_SEARCH_URL: ${ELASTIC_SEARCH_URL:-http://sitewideelasticsearch:9200}
      SERVICE_AUTH_TOKEN: ${SERVICE_AUTH_TOKEN:?please define a valid SERVICE_AUTH_TOKEN in your local system}
      ZEBEDEE_URL:        ${ZEBEDEE_URL:-http://zebedee:8082}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:28500/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
