version: "3.3"
services:
  dp-search-data-extractor:
    build:
      context: ${ROOT_SEARCH_DATA_EXTRACTOR:-../../../../dp-search-data-extractor}
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${ROOT_SEARCH_DATA_EXTRACTOR:-../../../../dp-search-data-extractor}:/dp-search-data-extractor
    expose:
      - "25800"
    ports:
      - 25800:25800
    restart: unless-stopped
    environment:
      BIND_ADDR:          ":25800"
      KAFKA_ADDR:         ${KAFKA_ADDR:-kafka-1:19092,kafka-2:19092,kafka-3:19092}
      KAFKA_VERSION:      ${KAFKA_VERSION:-3.1.0}
      ZEBEDEE_URL:        ${ZEBEDEE_URL:-http://zebedee:8082}
      DATASET_API_URL:    ${DATASET_API_URL:-http://dp-dataset-api:22000}
      SERVICE_AUTH_TOKEN: $SERVICE_AUTH_TOKEN
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:25800/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
