version: "3.3"
services:
  dp-topic-api:
    build:
      context: ${ROOT_TOPIC_API:-../../../../dp-topic-api}
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${ROOT_TOPIC_API:-../../../../dp-topic-api}:/dp-topic-api
    expose:
      - "25300"
    ports:
      - 25300:25300
    restart: unless-stopped
    environment:
      BIND_ADDR:         ":25300"
      MONGODB_BIND_ADDR: ${MONGODB_BIND_ADDR:-mongodb:27017}
      ZEBEDEE_URL:       ${ZEBEDEE_URL:-http://zebedee:8082}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:25300/health" ]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
