version: "3.3"
services:
  dp-topic-api:
    build:
      context: ../../../../dp-topic-api
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ../../../../dp-topic-api:/dp-topic-api
    expose:
      - "25300"
    ports:
      - 25300:25300
    restart: unless-stopped
    environment:
      BIND_ADDR:         ":25300"
      MONGODB_BIND_ADDR: ${MONGODB_BIND_ADDR:-mongodb:27017}
      ZEBEDEE_URL:       ${ZEBEDEE_URL:-http://zebedee:8082}
