version: "3.3"
services:
  florence:
    x-repo-url: "https://github.com/ONSdigital/florence"
    build:
      context: ${DP_REPO_DIR:-../../../..}/florence
      dockerfile: Dockerfile.local
    command:
      - reflex
      - -d
      - none
      - -c
      - ./reflex
    volumes:
      - ${DP_REPO_DIR:-../../../..}/florence:/florence
    expose:
      - "8081"
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      ENCRYPTION_DISABLED:        ${ENCRYPTION_DISABLED:-false}
      ENABLE_HOMEPAGE_PUBLISHING: "true"
      ENABLE_PERMISSION_API:      ${ENABLE_PERMISSION_API:-false}
      ENABLE_NEW_SIGN_IN:         ${ENABLE_NEW_SIGN_IN:-false}
      ENABLE_DATASET_IMPORT:      ${ENABLE_DATASET_IMPORT:-true}
      API_ROUTER_URL:             ${API_ROUTER_URL:-http://dp-api-router:23200}
      ROUTER_URL:                 ${FRONTEND_ROUTER_URL:-http://dp-frontend-router:20000}
      DATASET_CONTROLLER_URL:     ${DATASET_CONTROLLER_URL:-http://dp-publishing-dataset-controller:24000}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:8081/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
