version: "3.3"
services:
  sixteens:
    x-repo-url: "https://github.com/ONSdigital/sixteens"
    build:
      context: ${DP_REPO_DIR:-../../../..}/sixteens
      dockerfile: Dockerfile.local
    expose:
      - "9000"
    ports:
      - 9000:9000
    volumes:
      - ${DP_REPO_DIR:-../../../..}/sixteens:/sixteens
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:9000"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
