services:
  the-train:
    x-repo-url: "https://github.com/ONSdigital/the-train"
    build:
      context: ${DP_REPO_DIR:-../../../..}/the-train
      dockerfile: Dockerfile
    expose:
      - "8084"
    ports:
      - 8084:8084
    restart: unless-stopped
    volumes:
      - ${TRANSACTION_STORE:-${DP_REPO_DIR:-../../../..}/dp-zebedee-content/web/transactions}}:/transactions
      - ${WEBSITE:-${DP_REPO_DIR:-../../../..}/dp-zebedee-content/web/site}}:/site
    environment:
      TRANSACTION_STORE:           "/transactions"
      WEBSITE:                     "/site"
      PUBLISHING_THREAD_POOL_SIZE: 100
      PORT:                        8084
      DP_COLOURED_LOGGING:         "true"
      DP_LOGGING_FORMAT:           "pretty_json"
      MAX_FILE_UPLOAD_SIZE_MB:     -1
      MAX_REQUEST_SIZE_MB:         -1
      FILE_THRESHOLD_SIZE_MB:      0
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:8084/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
