version: "3.3"
services:
  the-train:
    x-repo-url: "https://github.com/ONSdigital/the-train"
    build:
      context: ${DP_REPO_DIR:-../../../..}/the-train
      dockerfile: Dockerfile
    expose:
      - "8084"
    ports:
      - 8084:8084
    restart: unless-stopped
    user: ${UID-1000}:${GID-1000}
    volumes:
      - ${zebedee_root:?please define a valid zebedee_root in your local system}:/zebedee_root
    environment:
      TRANSACTION_STORE:           "/zebedee_root/zebedee/transactions"
      WEBSITE:                     "/zebedee_root/zebedee/master"
      PUBLISHING_THREAD_POOL_SIZE: 100
      PORT:                        8084
      DP_COLOURED_LOGGING:         "true"
      DP_LOGGING_FORMAT:           "pretty_json"
      MAX_FILE_UPLOAD_SIZE_MB:     -1
      MAX_REQUEST_SIZE_MB:         -1
      FILE_THRESHOLD_SIZE_MB:      0
