services:
  zebedee-reader:
    x-repo-url: "https://github.com/ONSdigital/zebedee"
    build:
      context: ${DP_REPO_DIR:-../../../..}/zebedee/zebedee-reader
      dockerfile: Dockerfile.local
    expose:
      - "8082"
    ports:
      - 8082:8082
      - 8002:8002
    volumes:
      - ${content_dir:-${DP_REPO_DIR:-../../../..}/dp-zebedee-content/generated/web/site}:/content_dir
    restart: unless-stopped
    environment:
      FORMAT_LOGGING:         ${FORMAT_LOGGING:-true}
      PORT:                   "8082"
      JAVA_OPTS:              " -Xdebug -Xrunjdwp:transport=dt_socket,address=8002,server=y,suspend=n"
      RESTOLINO_CLASSES:      "target/classes"
      PACKAGE_PREFIX:         "com.github.onsdigital.zebedee.reader.api"
      CONTENT_DIR:            "/content_dir"
      OTEL_JAVAAGENT_ENABLED: ${OTEL_JAVAAGENT_ENABLED:-"false"}
      ELASTIC_SEARCH_SERVER:  ${ELASTIC_SEARCH_SERVER:-elasticsearch}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:8082/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
