version: "3.3"
services:
  zebedee-reader:
    x-repo-url: "https://github.com/ONSdigital/zebedee"
    build:
      context: ${DP_REPO_DIR:-../../../..}/zebedee/zebedee-reader
      dockerfile: Dockerfile.local
    expose:
      - "8082"
    ports:
      - 8082:8082
    volumes:
      - ${zebedee_root:?please define a valid zebedee_root in your local system}:/zebedee_root
    restart: unless-stopped
    environment:
      FORMAT_LOGGING:         ${FORMAT_LOGGING:-true}
      PORT:                   "8082"
      JAVA_OPTS:              " -Xdebug -Xrunjdwp:transport=dt_socket,address=8002,server=y,suspend=n"
      RESTOLINO_CLASSES:      "target/classes"
      CONTENT_DIR:            "content"
      PACKAGE_PREFIX:         "com.github.onsdigital.zebedee.reader.api"
      zebedee_root:           "/zebedee_root"
      OTEL_JAVAAGENT_ENABLED: ${OTEL_JAVAAGENT_ENABLED:-"false"}
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:8082/health"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: 10s
      retries: 10
