version: "3.3"
services:
  zebedee:
    build:
      context: ${ROOT_ZEBEDEE:-../../../../zebedee}/zebedee-reader
      dockerfile: Dockerfile.local
    expose:
      - "8082"
    ports:
      - 8082:8082
    volumes:
      - ${zebedee_root}:/zebedee_root
    restart: unless-stopped
    environment:
      FORMAT_LOGGING:    ${FORMAT_LOGGING:-true}
      PORT:              "8082"
      JAVA_OPTS:         " -Xdebug -Xrunjdwp:transport=dt_socket,address=8002,server=y,suspend=n"
      RESTOLINO_CLASSES: "target/classes"
      CONTENT_DIR:       "content"
      PACKAGE_PREFIX:    "com.github.onsdigital.zebedee.reader.api"
      zebedee_root:      "/zebedee_root"
